# .github/workflows/imagepush.yml
name: Docker Image Build and Push

on:
 workflow_call:

jobs:
  image_push:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: madhavip/petclinic:${{ github.sha }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: target/*.jar
      - name: Build Docker Image
        run: |
          ls ./target/spring-petclinic-3.4.0-SNAPSHOT.jar
          sudo docker build -t ${{ env.DOCKER_IMAGE }} .
          sudo docker save ${{ env.DOCKER_IMAGE }} > docker_image.tar

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: docker_image.tar

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: sudo docker push ${{ env.DOCKER_IMAGE }}