name: PetClinic Workflow
on:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            # Maven build
            # Sonar Qube
            # JFrog Artifactory