name: PetClinic Workflow
on:
    workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/maven.yml
    secrets: inherit
  sonar:
    uses: ./.github/workflows/sonarcloud.yml
    secrets: inherit
    needs: build
  test:
    uses: ./.github/workflows/test.yml
    needs: sonar
    secrets: inherit  
  imagepush:
    uses: ./.github/workflows/imagepush.yml
    needs: test
    secrets: inherit  