name: Maven Build

on:
  push:
    branches: [ main ]
      

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin' # Options: 'temurin', 'zulu', etc.
          cache: maven

      # Install dependencies and build the project
      - name: Build with Maven
        run: mvn clean install --batch-mode

      # Run tests
      - name: Run Tests
        run: mvn test --batch-mode

      # Optionally upload build artifacts
      - name: Upload Build Artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: target/*.jar
